// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterTankTool_WFA;

#nullable disable

namespace WaterTankTool_WFA.Migrations
{
    [DbContext(typeof(WaterTankDbContext))]
    [Migration("20240920214935_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WaterTankTool_WFA.Entity.SegmentProperties", b =>
                {
                    b.Property<int>("SegmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightInitial")
                        .HasColumnType("REAL");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentNumber");

                    b.ToTable("SegmentProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
