// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WaterTankTool_WFA.Migrations
{
    [DbContext(typeof(WaterTankDbContext))]
    partial class WaterTankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WaterTankTool_WFA.Entity.MaterialProperties", b =>
                {
                    b.Property<int>("MaterialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Density")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModulusOfElasticity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensileUltimateStress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensileYieldStress")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaterialNumber");

                    b.ToTable("MaterialProperties");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.SegmentProperties", b =>
                {
                    b.Property<int>("SegmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiameterFinal")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiameterInitial")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightInitial")
                        .HasColumnType("REAL");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentNumber");

                    b.ToTable("SegmentProperties");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.TankProperties", b =>
                {
                    b.Property<int>("TankNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectedArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalWeight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightOfSteel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightOfWater")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TankNumber");

                    b.ToTable("TankProperties");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.WindLoadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cf")
                        .HasColumnType("REAL");

                    b.Property<string>("Exposure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("G")
                        .HasColumnType("REAL");

                    b.Property<double>("I")
                        .HasColumnType("REAL");

                    b.Property<double>("Kd")
                        .HasColumnType("REAL");

                    b.Property<double>("Ke")
                        .HasColumnType("REAL");

                    b.Property<double>("Kzt")
                        .HasColumnType("REAL");

                    b.Property<double>("Q")
                        .HasColumnType("REAL");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.Property<double>("Zg")
                        .HasColumnType("REAL");

                    b.Property<double>("alpha")
                        .HasColumnType("REAL");

                    b.Property<double>("lambda")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WindLoadEnitity");
                });
#pragma warning restore 612, 618
        }
    }
}
